<?php


namespace App\Datatables;

use Sg\DatatablesBundle\Datatable\Column\Column;
use Sg\DatatablesBundle\Datatable\Filter\TextFilter;
use Sg\DatatablesBundle\Datatable\Column\ActionColumn;
use Sg\DatatablesBundle\Datatable\Editable\TextEditable;
class UserDatatable extends AbstractDatatable
{

    /**
     * {@inheritdoc}
     */
    public function buildDatatable(array $options = array())
    {
        parent::buildDatatable($options); // TODO: Change the autogenerated stub
        $this->columnBuilder
            ->add('nom', Column::class, array(
                'title'         => 'Nom',
                'searchable'    => true,
                'orderable'     => true,
            ))

            ->add('prenom', Column::class, array(
                'title'         => 'Prenom',
                'searchable'    => true,
                'orderable'     => true,
            ))

            ->add('email', Column::class, array(
                'title'         => 'Email',
                'searchable'    => true,
                'orderable'     => true,
            ))

            ->add('role', Column::class, array(
                'title'         => 'Role',
                'searchable'    => true,
                'orderable'     => true,
            ));
    }
    /**
     * {@inheritdoc}
     */
    public function getEntity()
    {
        return 'App\Entity\Users';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'UserDatatable';
    }

}